# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('owner', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=1024)),
                ('bedrooms', models.CharField(max_length=1024)),
            ],
        ),
    ]
