# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_area_parking_rockface_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='position',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
