# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0008_auto_20160406_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'område', 'verbose_name_plural': 'områden'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'klubb', 'verbose_name_plural': 'klubbar'},
        ),
        migrations.AlterModelOptions(
            name='clubadmin',
            options={'verbose_name': 'klubbadministratör', 'verbose_name_plural': 'klubbadministratörer'},
        ),
        migrations.AlterModelOptions(
            name='parking',
            options={'verbose_name': 'parkering', 'verbose_name_plural': 'parkeringar'},
        ),
        migrations.AlterModelOptions(
            name='rockface',
            options={'verbose_name': 'klippa', 'verbose_name_plural': 'klippor'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'led', 'verbose_name_plural': 'leder'},
        ),
        migrations.AlterField(
            model_name='area',
            name='clubs',
            field=models.ManyToManyField(to='django_api.Club', verbose_name='ansvarig klubb/klubbar'),
        ),
        migrations.AlterField(
            model_name='area',
            name='long_description',
            field=models.CharField(max_length=4000, null=True, verbose_name='lång beskrivning'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='namn'),
        ),
        migrations.AlterField(
            model_name='area',
            name='road_description',
            field=models.CharField(max_length=4000, null=True, verbose_name='väg beskrivning'),
        ),
        migrations.AlterField(
            model_name='area',
            name='short_description',
            field=models.CharField(max_length=300, null=True, verbose_name='kort beskrivning'),
        ),
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.TextField(verbose_name='adress'),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='epost'),
        ),
        migrations.AlterField(
            model_name='club',
            name='info',
            field=models.TextField(verbose_name='Information om klubben'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=255, verbose_name='namn'),
        ),
        migrations.AlterField(
            model_name='clubadmin',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.Club', verbose_name='klubb'),
        ),
        migrations.AlterField(
            model_name='clubadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='användare'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='django_api.Area', verbose_name='område'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='position',
            field=models.PositiveIntegerField(default=5, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='rockface',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rockfaces', to='django_api.Area', verbose_name='område'),
        ),
        migrations.AlterField(
            model_name='rockface',
            name='geo_data',
            field=models.CharField(max_length=3000, null=True, verbose_name='plats för klippan'),
        ),
        migrations.AlterField(
            model_name='rockface',
            name='long_description',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='lång beskrivning'),
        ),
        migrations.AlterField(
            model_name='rockface',
            name='name',
            field=models.CharField(max_length=150, verbose_name='namn'),
        ),
        migrations.AlterField(
            model_name='rockface',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='kort beskrivning'),
        ),
        migrations.AlterField(
            model_name='route',
            name='first_ascent_name',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='första bestigarens namn'),
        ),
        migrations.AlterField(
            model_name='route',
            name='first_ascent_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='år för första bestigning'),
        ),
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.CharField(choices=[('no', 'Ej graderad'), ('4a', '4a'), ('4b', '4b'), ('4c', '4c'), ('5a', '5a'), ('5b', '5b'), ('5c', '5c'), ('6a-', '6a-'), ('6a', '6a'), ('6a+', '6a+'), ('6b-', '6b-'), ('6b', '6b'), ('6b+', '6b+'), ('6c-', '6c-'), ('6c', '6c'), ('6c+', '6c+'), ('7a-', '7a-'), ('7a', '7a'), ('7a+', '7a+'), ('7b-', '7b-'), ('7b', '7b'), ('7b+', '7b+'), ('7c-', '7c-'), ('7c', '7c'), ('7c+', '7c+'), ('8a-', '8a-'), ('8a', '8a'), ('8a+', '8a+'), ('8b-', '8b-'), ('8b', '8b'), ('8b+', '8b+'), ('8c-', '8c-'), ('8c', '8c'), ('8c+', '8c+'), ('9a-', '9a-'), ('9a', '9a'), ('9a+', '9a+'), ('9b-', '9b-'), ('9b', '9b'), ('9b+', '9b+'), ('9c-', '9c-'), ('9c', '9c'), ('9c+', '9c+')], default='no', max_length=3, verbose_name='gradering'),
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='längd'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=150, verbose_name='namn'),
        ),
        migrations.AlterField(
            model_name='route',
            name='rock_face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='django_api.RockFace', verbose_name='klippa'),
        ),
        migrations.AlterField(
            model_name='route',
            name='short_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='kort beskrivning'),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Bo', 'Boulder'), ('Sp', 'Sport'), ('Tr', 'Trad'), ('Ai', 'Aid'), ('DW', 'DWS')], default='Sp', max_length=2, verbose_name='typ'),
        ),
    ]
