# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0010_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=django_api.models._image_file_path, verbose_name='bild')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='modified_by',
        ),
        migrations.CreateModel(
            name='AreaImage',
            fields=[
                ('baseimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_api.BaseImage')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.Area')),
            ],
            bases=('django_api.baseimage',),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
