# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0011_auto_20160411_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockFaceImage',
            fields=[
                ('baseimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_api.BaseImage')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.RockFace')),
            ],
            options={
                'verbose_name_plural': 'bilder på klippan',
                'verbose_name': 'bild på klippan',
            },
            bases=('django_api.baseimage',),
        ),
        migrations.AlterModelOptions(
            name='areaimage',
            options={'verbose_name': 'områdes bild', 'verbose_name_plural': 'områdes bild'},
        ),
        migrations.AlterModelOptions(
            name='baseimage',
            options={'verbose_name': 'bild', 'verbose_name_plural': 'bilder'},
        ),
    ]
