# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0014_auto_20160413_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockfaceimage',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='namn'),
        ),
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_api.RockFaceImage', verbose_name='bild'),
        ),
    ]
