# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0016_auto_20160420_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='replacing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_api.Area'),
        ),
        migrations.AddField(
            model_name='area',
            name='status',
            field=models.CharField(choices=[('b', 'väntar på godkännande'), ('a', 'Godkänt')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='rockface',
            name='replacing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_api.RockFace'),
        ),
        migrations.AddField(
            model_name='rockface',
            name='status',
            field=models.CharField(choices=[('b', 'väntar på godkännande'), ('a', 'Godkänt')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='route',
            name='replacing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_api.Route'),
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('b', 'väntar på godkännande'), ('a', 'Godkänt')], default='a', max_length=1),
        ),
    ]
