# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0017_auto_20160420_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='image',
        ),
        migrations.DeleteModel(
            name='AreaImage',
        ),
        migrations.DeleteModel(
            name='RockFaceImage',
        ),
        migrations.DeleteModel(
            name='BaseImage',
        ),
    ]
