# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0018_auto_20160420_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=django_api.models._image_file_path, verbose_name='bild')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='django_api.Area')),
            ],
            options={
                'verbose_name': 'områdes bild',
                'verbose_name_plural': 'områdes bild',
            },
        ),
        migrations.CreateModel(
            name='RockFaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=django_api.models._image_file_path, verbose_name='bild')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='namn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='kort beskrivning av bilden')),
                ('rockface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='django_api.RockFace')),
            ],
            options={
                'verbose_name': 'bild på klippan',
                'verbose_name_plural': 'bilder på klippan',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_api.RockFaceImage', verbose_name='bild'),
        ),
    ]
