# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 21:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0019_auto_20160420_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockface',
            name='geo_data',
            field=models.CharField(max_length=3000, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Geo-data is malformed.', regex='^(\\(\\d{1,3}\\.\\d+, \\d{1,3}\\.\\d+\\);)*$')], verbose_name='plats för klippan'),
        ),
    ]
