# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0020_auto_20160421_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustedadmin',
            name='user',
        ),
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.CharField(choices=[('c', 'Ändring som väntar på godkännande'), ('n', 'Ny som väntar på godkännande'), ('d', 'Väntar på att bli borttagen'), ('a', 'Godkänt')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='areaimage',
            name='status',
            field=models.CharField(choices=[('c', 'Ändring som väntar på godkännande'), ('n', 'Ny som väntar på godkännande'), ('d', 'Väntar på att bli borttagen'), ('a', 'Godkänt')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('c', 'Ändring som väntar på godkännande'), ('n', 'Ny som väntar på godkännande'), ('d', 'Väntar på att bli borttagen'), ('a', 'Godkänt')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='rockface',
            name='status',
            field=models.CharField(choices=[('c', 'Ändring som väntar på godkännande'), ('n', 'Ny som väntar på godkännande'), ('d', 'Väntar på att bli borttagen'), ('a', 'Godkänt')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='rockfaceimage',
            name='status',
            field=models.CharField(choices=[('c', 'Ändring som väntar på godkännande'), ('n', 'Ny som väntar på godkännande'), ('d', 'Väntar på att bli borttagen'), ('a', 'Godkänt')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('c', 'Ändring som väntar på godkännande'), ('n', 'Ny som väntar på godkännande'), ('d', 'Väntar på att bli borttagen'), ('a', 'Godkänt')], default='a', max_length=1),
        ),
        migrations.DeleteModel(
            name='TrustedAdmin',
        ),
    ]
