# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0022_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2016, 4, 23, 14, 12, 59, 675558, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='change',
            name='description',
            field=models.TextField(null=True, verbose_name='beskrivning'),
        ),
    ]
