# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0024_auto_20160423_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='datum'),
        ),
    ]
