# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_api.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_api', '0026_auto_20160427_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='CragfinderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='är betrodd')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cf_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='long_description',
            field=django_api.models.MarkDownTextField(max_length=4000, null=True, verbose_name='lång beskrivning'),
        ),
    ]
