# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0027_auto_20160427_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_message', models.CharField(max_length=255, verbose_name='kort meddelande')),
                ('long_message', models.TextField(blank=True, null=True, verbose_name='längre version av meddelandet')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='startdatum')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='stoppdatum')),
                ('rock_face', models.ManyToManyField(blank=True, to='django_api.RockFace', verbose_name='klippa')),
            ],
            options={
                'verbose_name': 'access',
                'verbose_name_plural': 'access',
            },
        ),
    ]
