# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0027_auto_20160427_0814'),
        ('django_api', '0020_auto_20160421_2302'),
    ]

    operations = [
    ]
