# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0028_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'accessdata', 'verbose_name_plural': 'accessdata'},
        ),
        migrations.AlterField(
            model_name='access',
            name='rock_face',
            field=models.ManyToManyField(to='django_api.RockFace', verbose_name='klippa'),
        ),
    ]
