# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0030_auto_20160614_2204'),
        ('django_api', '0029_auto_20160610_1705'),
    ]

    operations = [
    ]
