# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0031_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='routenode',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
