# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0032_routenode_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_nodes',
        ),
        migrations.RemoveField(
            model_name='routenode',
            name='order',
        ),
    ]
