# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0032_routenode_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='long_description',
            field=django_api.models.MarkDownTextField(help_text='Här finns utrymme att skriva en längre beskrivning av området.Formuläret stödjer <a href="https://guides.github.com/features/mastering-markdown/">markdown</a> formatering. Denna text visas på översiktssidan om ettområde i föraren.', max_length=4000, null=True, verbose_name='längre beskrivning'),
        ),
        migrations.AlterField(
            model_name='area',
            name='road_description',
            field=models.CharField(help_text='Här kan en ytterligare vägbeskrivning ges om det är önskvärt. (Området kommer att i ett senare steg att markeras på en karta). Max 4000 tecken.', max_length=4000, null=True, verbose_name='vägbeskrivning'),
        ),
        migrations.AlterField(
            model_name='area',
            name='short_description',
            field=models.CharField(help_text='Här kan du skriva en kortare beskrivning av området, max 300 tecken. Denna text är den beskrivning som visas överi föraren.', max_length=300, null=True, verbose_name='kortare beskrivning'),
        ),
    ]
