# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0033_auto_20160711_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteNodeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.RouteNode')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.Route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='route_nodes',
            field=models.ManyToManyField(through='django_api.RouteNodeRelation', to='django_api.RouteNode'),
        ),
    ]
